CREATE DATABASE servo;

CREATE TABLE stations (
    id SERIAL PRIMARY KEY,
    NAME TEXT,
    OWNER TEXT,
    ADDRESS VARCHAR(255),
    SUBURB VARCHAR(255),
    STATE VARCHAR(255),
    LATITUDE DOUBLE PRECISION,
    LONGITUDE DOUBLE PRECISION
);