CREATE DATABASE servo;

CREATE TABLE stations (
    id SERIAL PRIMARY KEY,
    OBJECTID INTEGER,
    FEATURETYPE TEXT,
    DESCRIPTION TEXT,
    CLASS TEXT,
    FID INTEGER,
    NAME TEXT,
    OPERATIONALSTATUS TEXT,
    OWNER TEXT,
    INDUSTRYID TEXT,
    ADDRESS VARCHAR(255),
    SUBURB VARCHAR(255),
    STATE VARCHAR(255),
    SPATIALCONFIDENCE INTEGER,
    REVISED INTEGER,
    COMMENT TEXT,
    LATITUDE DOUBLE PRECISION,
    LONGITUDE DOUBLE PRECISION
);

COPY stations (
    OBJECTID, FEATURETYPE, DESCRIPTION, CLASS, FID, NAME, OPERATIONALSTATUS, OWNER, INDUSTRYID, ADDRESS, SUBURB, STATE, SPATIALCONFIDENCE, REVISED, COMMENT, LATITUDE, LONGITUDE
)
FROM 'db/stations.csv'
CSV HEADER;

ALTER TABLE stations
DROP COLUMN OBJECTID,
DROP COLUMN FEATURETYPE,
DROP COLUMN DESCRIPTION,
DROP COLUMN CLASS,
DROP COLUMN FID,
DROP COLUMN OPERATIONALSTATUS,
DROP COLUMN INDUSTRYID,
DROP COLUMN SPATIALCONFIDENCE,
DROP COLUMN REVISED,
DROP COLUMN COMMENT;

ALTER TABLE stations
ADD logo TEXT DEFAULT '/images/petrol.png';

UPDATE stations 
SET logo = '/images/BP.png' WHERE owner = 'BP';

UPDATE stations 
SET logo = '/images/Caltex.png' WHERE owner = 'Caltex';

UPDATE stations 
SET logo = '/images/Shell.png' WHERE owner = 'Shell';

UPDATE stations 
SET logo = '/images/7Eleven.png' WHERE owner = '7-Eleven Pty Ltd';

UPDATE stations 
SET logo = '/images/United.jpg' WHERE owner = 'United';
